apiVersion: v1
kind: ConfigMap
metadata:
  name: generate-key-configmap
  namespace: dpki
data:
  config.yaml: |+
    APP:
      IP: "localhost"
      PORT: "9090"
      TIMEOUT: 60  
      CONTEXT:
        KEY: "/blockchain/dpki/v1/key"

    LOG:
      LEVEL: "debug"
      ENV: "dev"